apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-devstream-demo2
  labels:
    app: go-webapp-devstream-demo2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-webapp-devstream-demo2
  template:
    metadata:
      labels:
        app: go-webapp-devstream-demo2
    spec:
      containers:
      - name: go-webapp-devstream-demo2
        image: "YOUR_DOCKER_USERNAME/go-webapp-devstream-demo:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
